---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dependencies.admiral.io
spec:
  group: admiral.io
  names:
    kind: Dependency
    plural: dependencies
    shortNames:
    - dep
    - deps
    singular: dependency
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            properties:
              source:
                type: string
              identityLabel:
                type: string
              destinations:
                type: array
                items:
                  type: string
            type: object
