apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globaltrafficpolicies.admiral.io
spec:
  group: admiral.io
  names:
    kind: GlobalTrafficPolicy
    plural: globaltrafficpolicies
    shortNames:
    - gtp
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            properties:
              policy:
                items:
                  properties:
                    dnsPrefix:
                      type: string
                    lbType:
                      type: integer
                    target:
                      items:
                        properties:
                          region:
                            type: string
                          weight:
                            type: integer
                        type: object
                      type: array
                  type: object
                type: array
            type: object
